### ISSUE TITLE
Tried on Ubuntu 22.04 but it failed...

### ISSUE THREAD

**Issue by alexmyczko** [daduke/nfstop#1]
```
# ./nfstop.py 
Traceback (most recent call last):
  File "/usr/src/./nfstop.py", line 288, in <module>
    main()
  File "/usr/src/./nfstop.py", line 43, in main
    for line in execute([f"./{str(stp_file)}"]):
  File "/usr/src/./nfstop.py", line 144, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['./nfstop-temp.stp']' returned non-zero exit status 1.
```

```
 ./nfstop-temp.stp 
semantic error: while resolving probe point: identifier 'nfsd' at /usr/share/systemtap/tapset/linux/nfsd.stp:468:7
        source:       nfsd.proc3.read,
                      ^

semantic error: no match

Pass 2: analysis failed.  [man error::pass2]
Number of similar error messages suppressed: 5.
Rerun with -v to see them.
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
```

```
# ./nfstop-temp.stp -v
Pass 1: parsed user script and 484 library scripts using 132380virt/107400res/11492shr/95336data kb, in 190usr/10sys/198real ms.
semantic error: resolution failed in alias expansion builder

semantic error: while resolving probe point: identifier 'nfsd' at /usr/share/systemtap/tapset/linux/nfsd.stp:468:7
        source:       nfsd.proc3.read,
                      ^

semantic error: no match

semantic error: resolution failed in alias expansion builder

semantic error: resolution failed in alias expansion builder

semantic error: resolution failed in alias expansion builder

semantic error: resolution failed in alias expansion builder

semantic error: resolution failed in alias expansion builder

Pass 2: analyzed script: 1 probe, 0 functions, 0 embeds, 6 globals using 134832virt/110800res/12536shr/97788data kb, in 10usr/0sys/11real ms.
Pass 2: analysis failed.  [man error::pass2]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
```

Note didn't have/could not install `linux-image-amd64-dbg`

However all CONFIG options of /usr/share/doc/systemtap/README.Debian are given.

**Comment by daduke** [comment]
> Note didn't have/could not install linux-image-amd64-dbg

there's your issue I guess. No idea what Ubuntu is doing here.

**Comment by daduke** [comment]
on Ubuntu you need `linux-image-$(uname -r)-dbgsym`, see [here](https://wiki.ubuntu.com/Kernel/Systemtap#Where_to_get_debug_symbols_for_kernel_X.3F)

**Comment by alexmyczko** [comment]
That URL stopped updating 2018. Oh well never mind: "Ubuntu is Debian-based the same way milk is grass-based"
works with additional repos from https://wiki.ubuntu.com/Debug%20Symbol%20Packages - confirming it also works on ubuntu 22.04 with that dependency
